name: pytest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Run All Tests
        run: |
          poetry run pytest --cov-report term-missing --cov=odcnc tests
        env:
          PYTHONPATH: .:$PYTHONPATH
